config/routes.rb
Rails.application.routes.draw do
  resources :line_items
  resources :carts
  resources :store
  resources :movies
  devise_for :admins
  root 'movies#index', as:'movies_index'
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  before_action :set_movie, only: [:show, :edit, :update, :destroy]
  before_action :verify_user, only: [:index]

  # GET /movies
  # GET /movies.json
  def index
    @movies = Movie.all
  end

  # GET /movies/1
  # GET /movies/1.json
  def show
  end

  # GET /movies/new
  def new
    @movie = Movie.new
  end

  # GET /movies/1/edit
  def edit
  end

  # POST /movies
  # POST /movies.json
  def create
    @movie = Movie.new(movie_params)

    respond_to do |format|
      if @movie.save
        format.html { redirect_to @movie, notice: 'Movie was successfully created.' }
        format.json { render :show, status: :created, location: @movie }
      else
        format.html { render :new }
        format.json { render json: @movie.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /movies/1
  # PATCH/PUT /movies/1.json
  def update
    respond_to do |format|
      if @movie.update(movie_params)
        format.html { redirect_to @movie, notice: 'Movie was successfully updated.' }
        format.json { render :show, status: :ok, location: @movie }
      else
        format.html { render :edit }
        format.json { render json: @movie.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /movies/1
  # DELETE /movies/1.json
  def destroy
    @movie.destroy
    respond_to do |format|
      format.html { redirect_to movies_url, notice: 'Movie was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_movie
      @movie = Movie.find(params[:id])
    end

    def verify_user
      redirect_to store_index_path if user_signed_in?
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def movie_params
      params.require(:movie).permit(:image_url, :code, :name, :year, :genre, :price)
    end
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/views/movies/_form.html.erb
<%= form_for(movie) do |form| %>
  <% if movie.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(movie.errors.count, "error") %> prohibited this movie from being saved:</h2>

      <ul>
      <% movie.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= form.label :image_url %>
    <%= form.text_field :image_url, autofocus: true%>
  </div>

  <div class="field">
    <%= form.label :code %>
    <%= form.text_field :code %>
  </div>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :year %>
    <%= form.text_field :year %>
  </div>

  <div class="field">
    <%= form.label :genre %>
    <%= form.text_field :genre %>
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.number_field :price, step: :any %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/movies/edit.html.erb
<h1>Editing Movie</h1>

<%= render 'form', movie: @movie %>

<%= link_to 'Show', @movie %>

app/views/movies/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Movies</h1>

<table>
  <% @movies.each do |movie| %>
      <tr class="<%= cycle('list-line-odd', 'list-line-even') %>">
        <td>
          <%= image_tag(movie.image_url, class: 'list-image') %>
        </td>

        <td class="movie-information">
          <dl>
            <dt><%= movie.name %></dt>
            <dd><%= movie.code %></dd>
            <dd><%= movie.year %></dd>
            <dd><%= movie.genre %></dd>
            <dd><span class="price"><%= number_to_currency(movie.price) %></span></dd>
          </dl>
        </td>
        <% if admin_signed_in? %>
            <td class="list-action">
              <button type="button" class="btn btn-danger"><%= link_to 'Show', movie %></button><br />
              <button type="button" class="btn btn-danger"><%= link_to 'Edit', edit_movie_path(movie) %></button><br />
              <button type="button" class="btn btn-danger"><%= link_to 'Destroy', movie, method: :delete, data: { confirm: 'Are you sure?' } %> </button>
            </td>
        <% end %>
      </tr>
  <% end %>
</table>

app/views/movies/new.html.erb
<h1>New Movie</h1>

<%= render 'form', movie: @movie %>

<%= link_to 'Back', movies_path %>

app/views/movies/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <%= image_tag(@movie.image_url, width:"25%") %>
</p>

<p>
  <strong>Code:</strong>
  <%= @movie.code %>
</p>

<p>
  <strong>Name:</strong>
  <%= @movie.name %>
</p>

<p>
  <strong>Year:</strong>
  <%= @movie.year %>
</p>

<p>
  <strong>Genre:</strong>
  <%= @movie.genre %>
.movie_id<p>
  <strong>Price:</strong>
  $ <%= @movie.price %>
</p>

<%= link_to 'Edit', edit_movie_path(@movie) %>