config/routes.rb
Rails.application.routes.draw do
  resources :line_items
  resources :carts
  resources :store
  resources :movies
  devise_for :admins
  root 'movies#index', as:'movies_index'
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/cart.rb
class Cart
  include Mongoid::Document
  
  has_many :line_items, dependent: :destroy

  def total_price
    line_items.to_a.sum { |item| item.movie.price }    
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  before_action :set_cart, only: [:show, :edit, :update, :destroy]

  # GET /carts
  # GET /carts.json
  def index
    @carts = Cart.all
  end

  # GET /carts/1
  # GET /carts/1.json
  def show
  end

  # GET /carts/new
  def new
    @cart = Cart.new
  end

  # GET /carts/1/edit
  def edit
  end

  # POST /carts
  # POST /carts.json
  def create
    @cart = Cart.new(cart_params)

    respond_to do |format|
      if @cart.save
        format.html { redirect_to @cart, notice: 'Cart was successfully created.' }
        format.json { render :show, status: :created, location: @cart }
      else
        format.html { render :new }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /carts/1
  # PATCH/PUT /carts/1.json
  def update
    respond_to do |format|
      if @cart.update(cart_params)
        format.html { redirect_to @cart, notice: 'Cart was successfully updated.' }
        format.json { render :show, status: :ok, location: @cart }
      else
        format.html { render :edit }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /carts/1
  # DELETE /carts/1.json
  def destroy
    @cart.destroy
    respond_to do |format|
      format.html { redirect_to store_index_url, notice: 'Your cart is currently empty.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cart
      @cart = Cart.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cart_params
      params.fetch(:cart, {})
    end
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/views/carts/_form.html.erb
<%= form_with(model: cart, local: true) do |form| %>
  <% if cart.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(cart.errors.count, "error") %> prohibited this cart from being saved:</h2>

      <ul>
      <% cart.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.label @movie.name %>
  </div>

  <div class="field">
    <%= form.label :name %>
    <%= form.label @user.name %>
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.label @movie.price %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/carts/edit.html.erb
<h1>Editing Cart</h1>

<%= render 'form', cart: @cart %>

<%= link_to 'Show', @cart %> |
<%= link_to 'Back', carts_path %>

app/views/carts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Carts</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @carts.each do |cart| %>
      <tr>
        <td><%= link_to 'Show', cart %></td>
        <td><%= link_to 'Destroy', cart, method: :delete %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/carts/new.html.erb
<h1>New Cart</h1>

<%= render 'form', cart: @cart %>

<%= link_to 'Back', carts_path %>

app/views/carts/show.html.erb
<p id="notice"><%= notice %></p>

<h2>Your Cart</h2>
<ul>
  <% @cart.line_items.each do |item| %>
  <div class="cart">
    <h4><%= item.movie.name %></h4>
    <span class="price"><%= number_to_currency(item.movie.price) %></span>
  </div>
  <% end %>
  <div class="total">
    <h5>Total to Pay:<span class="total-price"><%= number_to_currency(@cart.total_price) %></span></h5>
  </div>
  <div class="button">
    <span><%= link_to 'Add more movies', store_index_path, class:"btn btn-danger"%></span>
  </div>
  <div class="button">
    <span><%= button_to 'Empty Cart', @cart, method: :delete, data: { confirm: 'Are you sure?' }, class:"btn btn-danger"%></span>
  </div>
  <div class="button">
    <span><%= button_to 'Make a rent', @cart, method: :delete, data: { confirm: %w{Success Canceled}.sample },class:"btn btn-danger"%></span>
  </div>

</div>
</ul>