config/routes.rb
Rails.application.routes.draw do
  resources :line_items
  resources :carts
  resources :store
  resources :movies
  devise_for :admins
  root 'movies#index', as:'movies_index'
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_login.html.erb
<% if user_signed_in? %>
  <li class="nav-link"><%= link_to 'Sing out', destroy_user_session_path, method: :delete %></li>
<% elsif admin_signed_in? %>
  <li class="nav-link"><%= link_to 'Sing out', destroy_admin_session_path, method: :delete %></li>
<% else %>
  <li class="nav-link"><%= link_to 'Sing in', new_user_session_path %></li>
  <li class="nav-link"><%= link_to 'Sing up', new_user_registration_path %></li>
<% end %>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand" href="/movies/">MovieHouse</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto ">
      <% if user_signed_in? %>
        <li class="nav-link"><%= link_to 'Home', store_index_path %></li>
      <% else %>
        <li class="nav-link"><%= link_to 'Movies', movies_index_path %></li>
      <% end %>
      <% if signed_in? %>
        <li class="nav-link"><%= link_to 'Show', carts_url %></li>
      <% end %>
      <% if admin_signed_in? %>
        <li class="nav-link"><%= link_to 'New Movie', new_movie_path %></li>
      <% end %>
      <%= render 'layouts/login' %>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Moviehouse</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class='<%= controller.controller_name %>'>
    <%= render "layouts/navigation" %>
    <div class="container">
      <%= yield %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    </div>
  </body>
</html>